config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "pets#index"

  resources :pets  do
    resources :appointments, only: [:new, :create, :index, :show]
  end
  resources :appointments, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :pet
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :pets, through: :bookmarks
end

app/models/pet.rb
class Pet < ApplicationRecord

  has_many :appointments
  has_many :doctors, through: :appointments


  def create_icon
    case self.species
    when "turtle"
      return "turtle.png"
    when "rabbit"
      return "rabbit.png"
    when "mouse"
      return "mouse.png"
     when "cat"
      return "cat.png"
    else
       return "dog.png"
    end
  end

  def set_background
     case self.species
    when "turtle"
      return "#f7d373"
    when "rabbit"
      return "#bfa2f7"
    when "mouse"
      return "#f3c4c6"
     when "cat"
      return "#c8d9f5"
    else
       return "#daf7fd"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def new
    @pet = Pet.find(params[:pet_id])
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @pet = Pet.find(params[:pet_id])
    @appointment.pet = @pet
    @appointment.save

    redirect_to pet_path(@pet)
  end

  private

  def appointment_params
    params.require(:appointment).permit(:reason, :doctor_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/new.html.erb
<h1 class="mt-4">Make Appointment for <%= @pet.name %></h1>


<%= simple_form_for [@pet, @appointment] do |f| %>
          <%= f.input :reason, placeholder: 'Enter the reason for the visit' %>
          <%= f.association :doctor, prompt: "Select a doctor", collection: Doctor.where(available: true), input_html: {data: { controller: "tom-select"}} %>
          <%= f.submit class: "apt-btn" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VetClinic</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pets/_appointmentcard.html.erb
<div class="petcard mt-3 hvr-grow">
  <h5 class="mt-2">Reason</h5>
  <h6><%= appointment.reason %></h6>


  <h5 class="mt-2">Date</h5>
  <h6><%= appointment.created_at.strftime("%Y-%m-%d") %></h6>

  <h5 class="mt-2">Doctor</h5>
  <h6><%= appointment.doctor.name %></h6>

</div>

app/views/pets/_petcard.html.erb
<div class="petcard mt-3 hvr-grow">

  <div class="img-container" style="background-color: <%= pet.set_background %>">
    <%= image_tag pet.create_icon %>
  </div>
  <h5 class="mt-2">Name</h5>
  <h6><%= pet.name %></h6>

  <h5 class="mt-2">Species</h5>
  <h6><%= pet.species.capitalize %></h6>

  <%= link_to "More", pet_path(pet), class: "more-btn" %>

</div>

app/views/pets/index.html.erb
<h1 class="mt-3">Patients</h1>
<div class="grid">
  <% @pets.each do |pet| %>
    <%= render "petcard", pet: pet %>
  <% end %>
</div>

app/views/pets/show.html.erb
<div class="info-visual-container mt-3">
  <h1 class="display-1"><%= @pet.name %></h1>
  <div class="img-container-show" style="background-color: <%= @pet.set_background %>">
      <%= image_tag @pet.create_icon %>
    </div>
</div>
<h2 class="display-4 show-species-text mb-5"><%= @pet.species.capitalize %></h2>
<%= link_to "Create appointment", new_pet_appointment_path(@pet), class: "apt-btn" %>


<h2 class="mt-5">Appoinments</h2>

<div class="grid">
  <% @pet.appointments.each do |appointment| %>
    <%= render "appointmentcard", appointment: appointment %>
  <% end %>
</div>